version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - flask-app-net
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  flask:
    image: anujpratapsingh/two-tier-backend:latest
    container_name: app-con
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: testdb
    networks:
      - flask-app-net
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  flask-app-net:
    external: true

volumes:
  mysql-data:
